spring:
  application:
    name: friendapp

  datasource:
    url: jdbc:mysql://localhost:3306/frienddb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

  config:
    import: optional:configserver:http://localhost:1111

server:
  port: 8802

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


